### ISSUE TITLE
how to change number of classes from kinetics to other multiclass dataset?

### ISSUE THREAD

**Issue by mbilalshaikh** [facebookresearch/hiera#21]
In the inference notebook. It is only suitable for kinetics-based datasets. Does Hiera library accepts different number for classes types?

**Comment by dbolya** [comment]
Yep, just specify `num_classes=<n>` when initializing the model. If you're using torch hub, just pass it is an argument in addition to the others.

Of course, if you change the number of classes while using a pre-trained model, the last layer's weights will get reset--so you'll have to finetune it on your classes yourself.
