### ISSUE TITLE
Table 13. Settings for AVA. learning rate=3.6?

### ISSUE THREAD

**Issue by justzhanghong** [facebookresearch/hiera#27]
<img width="530" alt="Snipaste_2024-02-26_15-22-35" src="https://github.com/facebookresearch/hiera/assets/39931535/dd4b7828-bb00-4062-994d-5ca616a19d75">

Hello, is the learning rate here sure to be 3.6? Is it this big? What is the initial learning rate for warm up?

**Comment by dbolya** [comment]
The global learning rate is indeed 3.6. It seemed big to me too, but that's what ended up working the best. We based our implementation off of the slowfast AVA configs, and those use a similar per-node learning rate (we use 0.225 per node * 16 nodes, and the defaults for slowfast are ~0.1 per node).

I don't believe we strayed from the default initial warmup in slowfast, which is 0.16 (0.01 per node * 16 nodes).

**Comment by justzhanghong** [comment]
Thanks for your reply and answer.
