### ISSUE TITLE
n_output_channels

### ISSUE THREAD

**Issue by liushawn618** [facebookresearch/hiera#32]
Hello,

Congrats on the great work again. What's the n_output_channels and downsample_rate of hiera_base_224?

**Comment by dbolya** [comment]
![Screenshot_2024-06-04-11-20-11-38_e2d5b3f32b79de1d45acd1fad96fbb0f](https://github.com/facebookresearch/hiera/assets/19721752/df2a944e-6aa4-4744-a816-5697d9b0e9a8)

B has 768 output channels with a 32x total downsample rate (224 -> 7).

**Comment by liushawn618** [comment]
Thank you for your timely reply. After changing n_output_channels into 768, I get RuntimeError: mat1 and mat2 shapes cannot be multiplied 64x1000 and 768x512. And then I just change it like this ![image](https://github.com/facebookresearch/hiera/assets/103125650/bc117802-7e4f-4e14-9e22-108c4caed8e5)
Now it's running, but is it ok to do like this?

**Comment by dbolya** [comment]
Can you share which script you're trying to use this with? Whether that's correct depends on what those variables specifically mean in that script.

**Comment by liushawn618** [comment]
I use this script "python scripts_method/train.py --demo --backbone hiera --setup p1 --method arctic_sf --trainsplit train --valsplit minival"

**Comment by dbolya** [comment]
> I use this script "python scripts_method/train.py --demo --backbone hiera --setup p1 --method arctic_sf --trainsplit train --valsplit minival"

In which repository is this?

**Comment by liushawn618** [comment]
I want to use hiera to extract features in this repository: https://github.com/zc-alexfan/arctic

**Comment by liushawn618** [comment]
The result seems not very good ![image](https://github.com/facebookresearch/hiera/assets/103125650/6d985d47-a5fc-4632-8694-37800887ae56)

**Comment by liushawn618** [comment]
The model is this https://github.com/zc-alexfan/arctic/blob/master/src/models/arctic_sf/model.py

And I changed 3 lines![image](https://github.com/facebookresearch/hiera/assets/103125650/d3a28ab5-dc86-488f-a327-09e5c7a08b59)

**Comment by dbolya** [comment]
Can you push your changes to a local repository? From what I can tell, 768 is the correct number of final features, so something may be going wrong elsewhere.

**Comment by liushawn618** [comment]
Thank you for your kind response.  My local respository is https://github.com/liushawn618/hiera_arctic_sf

**Comment by liushawn618** [comment]
The yellow line shows hiera as backbone. It seems to perform well during training but not so good during validation. <img width="1024" alt="截屏2024-06-05 下午2 46 37" src="https://github.com/facebookresearch/hiera/assets/103125650/245d81aa-b691-443d-8dd1-be458003cb89">
<img width="1015" alt="截屏2024-06-05 下午2 47 11" src="https://github.com/facebookresearch/hiera/assets/103125650/d69664c3-657a-40f1-97c3-883847f844d8">
<img width="978" alt="截屏2024-06-05 下午2 48 04" src="https://github.com/facebookresearch/hiera/assets/103125650/72921c46-0303-4800-9070-8e9901d6e631">

**Comment by dbolya** [comment]
Ah, I see what's going on. You're running Hiera in classification mode, not feature extraction. The backbone is returning an imagenet classification (`batch x n_classes`, which is why you see 64x1000).

The correct parameters are `n_output_channels` of 768, `downsample_rate` of 4 (though this seems to be unused) and to revert the changes to the second argument to `head_r, head_l, head_o`.

Then to get intermediate features for Heira, replace the backbone evaluation with:
```py
if self.args.heira:
    _, features = self.backbone(images, return_intermediates=True)
    features = features[-1]  # Get features from last stage
else:
   features = self.backbone(images)
```

**Comment by liushawn618** [comment]
Thank you so much! I try again with your help and now it's on the right track! <img width="1010" alt="截屏2024-06-05 下午7 58 21" src="https://github.com/facebookresearch/hiera/assets/103125650/38f388e1-dbf8-4ccc-9503-238d29441bc7">

**Comment by dbolya** [comment]
Great! Feel free to reopen this issue if you need more help.
